Update Tesla BLE commands to use accessory power for keeping car awake instead of Sentry Mode. Add 2 retries to cover BLE instabilities.

diff --git a/run/awake_start b/run/awake_start
--- a/run/awake_start
+++ b/run/awake_start
@@ -174,11 +174,13 @@ else
       elif [[ -n "${TESLA_BLE_VIN:+x}" ]]
       # Use Tesla BLE API to enable Sentry Mode
       then
-        if /root/bin/tesla-control -ble -key-file /root/.ble/key_private.pem -vin "${TESLA_BLE_VIN^^}" sentry-mode on
+        if (r=3
+          until /root/bin/tesla-control -ble -key-file /root/.ble/key_private.pem -vin "${TESLA_BLE_VIN^^}" keep-accessory-power on
+            do ((--r))||exit 1; sleep 5; done)
         then
-          log "Tesla BLE: Command sent to enable Sentry Mode."
+          log "Tesla BLE: Command sent to keep accessory power on."
         else
-          log "Tesla BLE: Failed to set Sentry Mode."
+          log "Tesla BLE: Failed to set keep accessory power."
         fi
       elif [[ -n "${KEEP_AWAKE_WEBHOOK_URL:+x}" ]]
       # Use webhook to send start command
diff --git a/run/awake_stop b/run/awake_stop
--- a/run/awake_stop
+++ b/run/awake_stop
@@ -88,11 +88,13 @@ case "${SENTRY_CASE}" in
     elif [[ -n "${TESLA_BLE_VIN:+x}" ]]
     then
       # Use Tesla BLE API to disable Sentry Mode
-      if /root/bin/tesla-control -ble -key-file /root/.ble/key_private.pem -vin "${TESLA_BLE_VIN^^}" sentry-mode off
+      if (r=3
+          until /root/bin/tesla-control -ble -key-file /root/.ble/key_private.pem -vin "${TESLA_BLE_VIN^^}" keep-accessory-power off
+            do ((--r))||exit 1; sleep 5; done)
       then
-        log "Tesla BLE: Command sent to disable Sentry Mode."
+        log "Tesla BLE: Command sent to disable keep accessory power."
       else
-        log "Tesla BLE: Failed to set Sentry Mode."
+        log "Tesla BLE: Failed to set keep accessory power."
       fi
 
     elif [[ -n "${KEEP_AWAKE_WEBHOOK_URL:+x}" ]]
